<?php

namespace AngryProgrammers\BlogBundle\Entity;

/**
 * LikeBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeBilletRepository extends \Doctrine\ORM\EntityRepository
{
}
