angry_programmers_blog_homepage:
    path:     /
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:index }

angry_programmers_blog_post:
    path: /post/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:post }

angry_programmers_blog_admin:
    path: /admin
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:admin }

angry_programmers_blog_ajoutBillet:
    path: /admin/ajoutBillet
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:ajoutBillet }
