angry_programmers_blog_homepage:
    path:     /{page}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*

angry_programmers_blog_post:
    path: /post/{slug}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:post }

angry_programmers_blog_admin:
    path: /admin
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:admin }

angry_programmers_crud_new:
    path: /admin/new
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:new }

angry_programmers_crud_edit:
    path: /admin/edit/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:edit }

angry_programmers_crud_delete:
    path: /admin/delete/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:delete }

angry_programmers_blog_likeBillet:
    path: /like/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:like }
