angry_programmers_blog_homepage:
    path:     /
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:index }

angry_programmers_blog_post:
    path: /post/{slug}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:post }

angry_programmers_blog_admin:
    path: /admin
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:admin }

angry_programmers_blog_ajoutBillet:
    path: /admin/ajoutBillet
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:ajoutBillet }

angry_programmers_blog_modifierBillet:
    path: /admin/modifierBillet/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:modifierBillet }

angry_programmers_blog_supprimerBillet:
    path: /admin/supprimerBillet/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:supprimerBillet }
