angry_programmers_blog_homepage:
    path:     /
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:index }

angry_programmers_blog_post:
    path: /post/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:post }
