angry_programmers_blog_homepage:
    path:     /
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:index }

angry_programmers_blog_post:
    path: /post/{slug}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:post }

angry_programmers_blog_admin:
    path: /admin
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:admin }

angry_programmers_crud_ajoutBillet:
    path: /admin/ajoutBillet
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:ajoutBillet }

angry_programmers_crud_modifierBillet:
    path: /admin/modifierBillet/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:modifierBillet }

angry_programmers_crud_supprimerBillet:
    path: /admin/supprimerBillet/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Crud:supprimerBillet }

angry_programmers_blog_likeBillet:
    path: /likeBillet/{id}
    defaults: { _controller: AngryProgrammersBlogBundle:Blog:likeBillet }
